### ISSUE TITLE
typescript should a peerDependency, not a dependency

### ISSUE THREAD

**Issue by kevinphelps** [tsne/rollup-plugin-tsc#3]
The user should be able use whatever version of TypeScript they want to install.

**Comment by tsne** [comment]
Hi @kevinphelps.

As I understand it, peer dependencies are used for plugins to define the compatible versions of the host package. Since `rollup-plugin-tsc` actually depends on the `typescript` package (i.e. it imports it), I think `typescript` should not be seen as a peer dependency here. It would also add an extra step for the users to install `typescript` on their own.
Maybe you can elaborate a little bit more on your use case. Why do you want to specify a fixed Typescript version?
